spring.application.name=api-gateway

server.port=8080

#Eureka client
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Auth service configuration
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

# Batch processor service configuration
spring.cloud.gateway.server.webflux.routes[1].id=batch-processor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://batch-processor-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/batch/**

# Clients service configuration
spring.cloud.gateway.server.webflux.routes[2].id=clients-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://clients-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/**

# News service configuration
spring.cloud.gateway.server.webflux.routes[3].id=news-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://news-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/news/**

# Payments service configuration
spring.cloud.gateway.server.webflux.routes[4].id=payments-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://payments-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/payments/**

# Products service configuration
spring.cloud.gateway.server.webflux.routes[5].id=products-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://products-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/products/**

# Reports service configuration
spring.cloud.gateway.server.webflux.routes[6].id=reports-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://reports-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/reports/**

# Discovery server configuration
spring.cloud.gateway.server.webflux.routes[7].id=discovery-server
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/eureka/web
spring.cloud.gateway.server.webflux.routes[7].filters[0]=SetPath=/

# Discovery server static routes
spring.cloud.gateway.server.webflux.routes[8].id=discovery-server-static
spring.cloud.gateway.server.webflux.routes[8].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/eureka/**

# Security configuration
spring.cloud.gateway.server.webflux.default-filters[0]=SaveSession
spring.cloud.gateway.server.webflux.default-filters[1]=TokenRelay

# Gateway configuration
spring.cloud.gateway.server.webflux.default-filters[2]=Retry=3

# Keycloak configuration
spring.security.oauth2.client.provider.keycloak.issuer-uri=${SPRING_OAUTH2_ISSUER_URI}
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.client-id=${SPRING_OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${SPRING_OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak

# Log
logging.level.root=info
logging.level.org.springframework.cloud.gateway=trace
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=info